- job-template:
    name: 'ui-autotests_2'
    description: 'Running UI autotests'
    project-type: pipeline
    concurrent: true
    logrotate:
      daysToKeep: 30
      numToKeep: 10
    parameters:
      - string:
          name: BRANCH
          default: master
          description: "Branch for tempest barbican API tests"
      - string:
          name: BASE_URL
          default: https://otus.ru
          description: "Hostname of stand"
      - string:
          name: BROWSER_NAME
          default: chrome
          description: "Browser name"
      - string:
          name: BROWSER_VERSION
          default: "104.0"
          description: "Browser version"
      - string:
          name: FILTER
          default: "QA"
          description: "Filter by name of courses"
    pipeline-scm:
      scm:
      - git-ui-autotests
      script-path: jenkins/ui_autotests.groovy