---

- view:
    name: QA_2
    view-type: list
    description: |
      QA Jobs
    filter-executors: true
    filter-queue: true
    job-name:
      - 'ui-autotests_2'
    columns:
      - status
      - weather
      - job
      - last-success
      - last-failure
      - last-duration
      - build-button